audit_header: false
title: Cambridge Real Estate Video Blog with Jerry Van Leeuwen
description: >-
  Our mission at Van Leeuwen Real Estate Advisors is to be your best resource
  for Cambridge real estate advice. Whether you are a buyer, seller, or
  investor, our team of professionals can answer any questions you might have
  about real estate. If you are looking to buy or sell a home, you can get all
  the information and the latest updates, tips, and tricks from The Van Leeuwen
  Real Estate Advisors, your professional Cambridge Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Jerry Van Leeuwen
  title:
  license_number:
  about_markdown: >-
    Jerry has been helping families and individuals find and secure their dream
    homes for many years now. His family has been his driving force and they
    inspire him to maintain a strong work ethic. Jerry's previous experience as
    a paramedic has helped him develop a passion for the positive aspects of
    life.
  brand: Van Leeuwen Real Estate Advisors
  brokerage:
  market: Cambridge
  address: '1165 Franklin Blvd. CAMBRIDGE, Ontario N1R8E1'
  phone: 519-772-4328
  phone_type:
  phone2:
  phone2_type:
  email: jerry.j.vanleeuwen@gmail.com
  url: 'http://www.vlahomelistings.com/'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.vlahomelistings.com/images/landing/homeworth/index.asp
  second_CTA_text: Home Search
  second_CTA_URL: http://www.vlahomelistings.com/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Cambridge Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: http://www.vlahomelistings.com/images/landing/homeworth/index.asp
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Cambridge Home?
    CTA_text2: Search the entire MLS for your Cambridge home.
    CTA_link_text2: Search the MLS
    CTA_url2: http://www.vlahomelistings.com/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Cambridge Real Estate Podcast with Jerry Van Leeuwen
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Cambridge
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Van Leeuwen Real Estate Advisors -
    your professional Cambridge Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Cambridge, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Jerry Van Leeuwen
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Cambridge Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#0f75bc'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'